### ISSUE TITLE
API limit hit on build

### ISSUE THREAD

**Issue by crawlem** [crawlem/film-club#53]
Multiple builds in a short space of time hit an Airtable API rate limit. This happens locally and on GitHub builds when running a "generate" build i.e. static file production. 

In generate mode it seems API calls are made for each page being flattened. In local dev mode the APIs are called once on first page load, then stored in state for subsequent page views.

```
Error:   /film/receDsZ0IhqQlwDlI

HTTPError: Too Many Requests
    at fn (node_modules/ky/index.js:317:0)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Ky._retry (node_modules/ky/index.js:412:0)
    at async http_HTTP.module.exports.http_HTTP.<computed> [as get] (node_modules/.cache/nuxt/http.js:95:0)
    at async Store.loadAllData (store/filmStore.js:28:0)
```
The line of code in question is
`const meetingsResponse = await this.$airtable.get('/Meetings?sort[0][field]=Date&sort[0][direction]=desc') // &filterByFormula={Date} >= TODAY()`

**Comment by crawlem** [comment]
One way around this might be making 1 request to the API to return multiple (all?) movies in one go e.g. using the /search/movie API?

**Comment by crawlem** [comment]
Error:   /film/receDsZ0IhqQlwDlI

HTTPError: Too Many Requests
    at fn (node_modules/ky/index.js:317:0)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Ky._retry (node_modules/ky/index.js:412:0)
    at async http_HTTP.module.exports.http_HTTP.<computed> [as get] (node_modules/.cache/nuxt/http.js:95:0)
    at async Store.loadAllData (store/filmStore.js:28:0)

**Comment by crawlem** [comment]
Not a perfect fix, but caching using the default store (index.js) has helped. Rather than calling the Airtable API every time a page is rendered during `generate`, it's now called 3 times (I think one for each Vue page). Ideally of course this would just be 1 time!
